{
 "title": "ISUCON",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "finish_time", "query": "2023-11-25T18:00:00" }
  ]
 },
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 18, "x": 3, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "systemd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(systemd_process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "{{name}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemd_process_resident_memory_bytes",
     "legendFormat": "{{name}}-{{instance}}"
    }
   ]
  },
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "total-{{instance}}" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "used-{{instance}}"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "description": "IN が +",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[$__rate_interval])",
     "legendFormat": "IN:{{device}}-{{instance}}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total[$__rate_interval])",
     "legendFormat": "OUT:{{device}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "netdata_disk_io_KiB_persec_average",
     "legendFormat": "{{instance}}-{{dimension}}"
    }
   ]
  }
 ]
}