---
- hosts: all
  name: "Stop observers"
  remote_user: isucon
  vars_files: ../vars/vars.yml
  tasks:
    - name: "Stop promtail"
      ansible.builtin.systemd:
        name: promtail
        state: stopped
        enabled: false
    - name: "Stop node_exporter"
      ansible.builtin.systemd:
        name: node_exporter
        state: stopped
        enabled: false
    - name: "Stop systemd_exporter"
      ansible.builtin.systemd:
        name: systemd_exporter
        state: stopped
        enabled: false
